import fs from 'node:fs';
import path from 'node:path';
import { projectDir } from '../core/paths.js';

/**
 * Rules generator (Phase 2): render one canonical rule set into the
 * instruction-file format of each supported AI tool.
 */

export interface RuleTarget {
  id: string;
  name: string;
  /** Output path relative to project root. */
  file: string;
  render(rules: string, projectName: string): string;
}

const HEADER = `<!-- Generated by devpilot generate — edit .devpilot/rules.md and re-run to update. -->`;

function standardBody(rules: string, projectName: string, tool: string): string {
  return `${HEADER}

# ${projectName} — Instructions for ${tool}

${rules}
`;
}

export const RULE_TARGETS: RuleTarget[] = [
  {
    id: 'claude',
    name: 'Claude Code',
    file: 'CLAUDE.md',
    render: (rules, project) => standardBody(rules, project, 'Claude'),
  },
  {
    id: 'cursor',
    name: 'Cursor',
    file: path.join('.cursor', 'rules', 'devpilot.mdc'),
    render: (rules, project) => `---
description: ${project} project rules (generated by DevPilot)
alwaysApply: true
---

${rules}
`,
  },
  {
    id: 'codex',
    name: 'Codex CLI',
    file: 'AGENTS.md',
    render: (rules, project) => standardBody(rules, project, 'Codex'),
  },
  {
    id: 'copilot',
    name: 'GitHub Copilot',
    file: path.join('.github', 'copilot-instructions.md'),
    render: (rules, project) => standardBody(rules, project, 'GitHub Copilot'),
  },
  {
    id: 'gemini',
    name: 'Gemini CLI',
    file: 'GEMINI.md',
    render: (rules, project) => standardBody(rules, project, 'Gemini'),
  },
];

export const DEFAULT_RULES = `## General

- Read .devpilot/context.md and .devpilot/architecture.md before making changes.
- Keep changes small and focused; follow existing patterns in the codebase.
- Write or update tests alongside code changes.
- Update documentation when behavior changes.

## Code Style

- Match the project's existing formatting, naming and idioms.
- Prefer clear, self-explanatory code over comments.

## Safety

- Never commit secrets, API keys or credentials.
- Ask before running destructive commands.
`;

/** Read the canonical rules from .devpilot/rules.md (create default if missing). */
export function loadRules(root: string): string {
  const file = path.join(projectDir(root), 'rules.md');
  if (!fs.existsSync(file)) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, DEFAULT_RULES);
  }
  return fs.readFileSync(file, 'utf8');
}

export interface GeneratedFile {
  target: string;
  file: string;
}

export function generateRules(root: string, projectName: string, only?: string[]): GeneratedFile[] {
  const rules = loadRules(root);
  const targets = only?.length ? RULE_TARGETS.filter((t) => only.includes(t.id)) : RULE_TARGETS;
  const written: GeneratedFile[] = [];
  for (const target of targets) {
    const out = path.join(root, target.file);
    fs.mkdirSync(path.dirname(out), { recursive: true });
    fs.writeFileSync(out, target.render(rules.trim(), projectName));
    written.push({ target: target.name, file: target.file });
  }
  return written;
}
