import fs from 'node:fs';
import path from 'node:path';
import { projectDir } from '../core/paths.js';
import { signatureOf } from '../generate/manifest.js';

/**
 * Rules generator (Phase 2): render one canonical rule set into the
 * instruction-file format of each supported AI tool.
 */

export interface RuleTarget {
  id: string;
  name: string;
  /** Output path relative to project root. */
  file: string;
  render(rules: string, projectName: string): string;
}

const HEADER = `<!-- Generated by knowa generate — edit .knowa/rules.md and re-run to update. -->`;

function standardBody(rules: string, projectName: string, tool: string): string {
  return `${HEADER}

# ${projectName} — Instructions for ${tool}

${rules}
`;
}

export const RULE_TARGETS: RuleTarget[] = [
  {
    id: 'claude',
    name: 'Claude Code',
    file: 'CLAUDE.md',
    render: (rules, project) => standardBody(rules, project, 'Claude'),
  },
  {
    id: 'cursor',
    name: 'Cursor',
    file: path.join('.cursor', 'rules', 'knowa.mdc'),
    render: (rules, project) => `---
description: ${project} project rules (generated by Knowa)
alwaysApply: true
---

${rules}
`,
  },
  {
    id: 'codex',
    name: 'Codex CLI',
    file: 'AGENTS.md',
    render: (rules, project) => standardBody(rules, project, 'Codex'),
  },
  {
    id: 'copilot',
    name: 'GitHub Copilot',
    file: path.join('.github', 'copilot-instructions.md'),
    render: (rules, project) => standardBody(rules, project, 'GitHub Copilot'),
  },
  {
    id: 'gemini',
    name: 'Gemini CLI',
    file: 'GEMINI.md',
    render: (rules, project) => standardBody(rules, project, 'Gemini'),
  },
];

export const DEFAULT_RULES = `## Working agreement — non-negotiable

- Read .knowa/rules.md, docs/architecture.md and docs/conventions.md, plus
  the files you are about to change, before your first edit. Say what you read.
- Put new code in the module that already owns the concern, in the patterns
  already there. Get approval before adding a module, dependency or layer.
- Never rewrite, reorganize or regenerate documentation as a side effect of a
  code change. Edit only what the change made wrong, and name every doc file
  you touched in your summary.

## General

- Read .knowa/context.md and docs/architecture.md before making changes.
- Keep changes small and focused; follow existing patterns in the codebase.
- Write or update tests alongside code changes.

## Code Style

- Match the project's existing formatting, naming and idioms.
- Prefer clear, self-explanatory code over comments.

## Safety

- Never commit secrets, API keys or credentials.
- Ask before running destructive commands.
`;

/** Read the canonical rules from .knowa/rules.md (create default if missing). */
export function loadRules(root: string): string {
  const file = path.join(projectDir(root), 'rules.md');
  if (!fs.existsSync(file)) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, DEFAULT_RULES);
  }
  return fs.readFileSync(file, 'utf8');
}

export interface GeneratedFile {
  target: string;
  file: string;
}

/**
 * Mirror files whose content no longer renders from the current
 * `.knowa/rules.md`.
 *
 * The kit tells users to edit `.knowa/rules.md` and re-run, but nothing
 * detected the window in between: a hand-edited rules file whose mirrors still
 * carry the previous text. `knowa sync` uses this to close it.
 *
 * Comparison is on the manifest's cosmetic-insensitive signature, so a repo
 * that runs a markdown formatter over its tool files does not read as
 * permanently stale.
 */
export function staleMirrors(root: string, projectName: string, only?: string[]): string[] {
  const file = path.join(projectDir(root), 'rules.md');
  if (!fs.existsSync(file)) return [];
  const rules = fs.readFileSync(file, 'utf8').trim();
  const stale: string[] = [];
  for (const target of targetsFor(only)) {
    const out = path.join(root, target.file);
    // A mirror this project never had is not stale — it was never claimed.
    if (!fs.existsSync(out)) continue;
    try {
      if (
        signatureOf(fs.readFileSync(out, 'utf8')) !== signatureOf(target.render(rules, projectName))
      )
        stale.push(target.file);
    } catch {
      // Unreadable mirror: leave it alone rather than guess.
    }
  }
  return stale;
}

function targetsFor(only?: string[]): RuleTarget[] {
  return only?.length ? RULE_TARGETS.filter((t) => only.includes(t.id)) : RULE_TARGETS;
}

export function generateRules(root: string, projectName: string, only?: string[]): GeneratedFile[] {
  const rules = loadRules(root);
  const targets = targetsFor(only);
  const written: GeneratedFile[] = [];
  for (const target of targets) {
    const out = path.join(root, target.file);
    fs.mkdirSync(path.dirname(out), { recursive: true });
    fs.writeFileSync(out, target.render(rules.trim(), projectName));
    written.push({ target: target.name, file: target.file });
  }
  return written;
}
